### ISSUE TITLE
catalyst support?

### ISSUE THREAD

**Issue by jlippold** [helpcrunch/sdk-cocoapods#3]
I have a app that runs on iOS, iPadOS and macOS, but this pod doesn't build on macOS.

Can you guys update this pod to support [Catalyst](https://developer.apple.com/mac-catalyst/)?

Thanks in advance

**Comment by Fishkiller** [comment]
Yes, we're looking into supporting Catalyst, but there are some issues to get there at the moment. Since we're doing fat library - Catalyst uses it's own version of x86_64 architecture and we can't include it, because we already included x86_64 for iOS Simulator. We can't compile it in x86_64h because Socket.io library uses libz that is not compiled for this architecture. And finally we can't use new XCFramework, because we want to support Xcode 10. We will switch to XCFramework as soon as Xcode 10 will be outdated.
We can offer you an option to compile version of our sdk specially for Catalyst, but it won't contain architecture for ios Simulator and you need to contact our support in order to ask for it.

PS. This is and old SDK. You can find latest version here: https://github.com/helpcrunch/helpcrunchsdk-ios/

**Comment by jlippold** [comment]
Thanks for the info @Fishkiller, but it sounds above my head to compile myself. Is there an easy way to exclude this pod from macos builds of my app? I want to use the pod on iOS but not on macOS, but I can't build at all if I include your pod. Thanks again

**Comment by Fishkiller** [comment]
No problem, in this case I recommend you to look into **platform** section in podfile. You defer which pods to install for which platform. https://guides.cocoapods.org/syntax/podfile.html#platform
You might need to create two targets: for iOS and MacOS
